image: dtg/puppet:16.04

stages:
  - check
  - test
  - style

syntax:
  stage: check
  script:
    - "find . -name '*.pp' | xargs puppet parser validate"
  only:
    - branches

base-apply:
  stage: test
  script:
    - git submodule init -q
    - git submodule update -q
    - FACTER_fqdn=default.dtg.cl.cam.ac.uk puppet apply --noop --modulepath=modules --node_name_value=default.dtg.cl.cam.ac.uk manifests/nodes/
  only:
    - branches

lint-error:
  stage: test
  script:
    - puppet-lint --error-level error .
  only:
    - branches

lint-warn:
  stage: style
  allow_failure: true
  script:
    - puppet-lint --fail-on-warnings --error-level warning .
  only:
    - branches
