image: dtg/puppet:16.04

stages:
  - check
  - test
  - style
  - integration

syntax:
  stage: check
  script:
    - "find . -name '*.pp' | xargs puppet parser validate"
  only:
    - branches

base-apply:
  stage: test
  script:
    - git submodule init -q
    - git submodule update -q
    - FACTER_hostname=default FACTER_fqdn=default.dtg.cl.cam.ac.uk puppet apply --noop --modulepath=modules --node_name_value=default.dtg.cl.cam.ac.uk manifests/nodes/
  only:
    - branches

lint-error:
  stage: test
  script:
    - puppet-lint --error-level error manifests/
    - puppet-lint --error-level error modules/bayncore/
    - puppet-lint --error-level error modules/dtg/
    - puppet-lint --error-level error modules/exim/
    - puppet-lint --error-level error modules/gpg/
    - puppet-lint --error-level error modules/munin/
    - puppet-lint --error-level error modules/nagios/
  only:
    - branches

lint-warn:
  stage: style
  allow_failure: true
  script:
    - puppet-lint --fail-on-warnings --error-level warning manifests/
    - puppet-lint --fail-on-warnings --error-level warning modules/bayncore/
    - puppet-lint --fail-on-warnings --error-level warning modules/dtg/
    - puppet-lint --fail-on-warnings --error-level warning modules/exim/
    - puppet-lint --fail-on-warnings --error-level warning modules/gpg/
    - puppet-lint --fail-on-warnings --error-level warning modules/munin/
    - puppet-lint --fail-on-warnings --error-level warning modules/nagios/
  only:
    - branches

shellcheck:
  stage: style
  allow_failure: true
  script:
    - find modules/{bayncore,dtg,exim,gpg,munin,nagios}/ -name '*.sh' -print0 | xargs -0 shellcheck
  only:
    - branches

apply-all:
  stage: integration
  script:
    - git submodule init -q
    - git submodule update -q
    - apt-get update -qq
    - FACTER_hostname=default FACTER_fqdn=default.dtg.cl.cam.ac.uk puppet apply --modulepath=modules --node_name_value=default.dtg.cl.cam.ac.uk manifests/nodes/
    - ./test-all-puppet.py
  only:
    - branches
