image: ubuntu:16.04

before_script:
  - apt-get update -qq

test-apply:
  stage: test
  allow_failure: true
  script:
    - apt-get install -y puppet-common git > /dev/null
    - git submodule init
    - git submodule update
    - FACTER_fqdn=default.dtg.cl.cam.ac.uk puppet apply --noop --modulepath=modules --node_name_value=default.dtg.cl.cam.ac.uk manifests/nodes/
  only:
    - branches

lint:
  stage: test
  script:
    - apt-get install -y puppet-lint > /dev/null
    - puppet-lint .
  only:
    - branches
